settings:
  prefix: "&8[&c&lBANSYSTEM&r&8] &8» "
  ban-title: "&8[&c&lBANSYSTEM&r&8]"
  ban-broadcast-prefix: "&c&lBAN &8» "
  unban-broadcast-prefix: "&a&lUNBAN &8» "

mysql:
  host: localhost
  port: 3306
  database: proxybans
  user: root
  password: password
  jdbc-parameters: "useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&connectTimeout=5000&useUnicode=true&characterEncoding=UTF-8"
